### ISSUE TITLE
Please Update 

### ISSUE THREAD

**Issue by LUNACYGG** [GladUrBad/Nova#1]
This anti-cheat is terrible!
Easy bypass flight，Speed
Almost no killaura detection
I hope you will fix it.

**Comment by LUNACYGG** [comment]
Bypass in FDPClient
Fly: FakeGround & HyCraft Mode
Speed: AAC4Bhop Mode

**Comment by xkeksi** [comment]
read the code first to understand why it barely detect shit he didnt want to spoonfeed skids
